import random
    
def yieldString(): #returns a random string serving as main sentence
        strings = []
        strings.append("The tranquility of a mountaintop sunrise is unparalleled. As the sun's first rays break over the horizon, painting the world in shades of gold and pink, a profound sense of serenity descends upon the landscape. The majestic peaks cast long shadows that seem to stretch infinitely, and the world is bathed in ethereal light. It's a reminder that in nature's embrace, one can find solace and beauty beyond words. The stillness is punctuated only by the soft whispers of the breeze and the distant calls of birds awakening. The moment is a meditation on the magnificence of the natural world and a testament to the need to preserve its pristine beauty.")
        strings.append("In the heart of a bustling city, the energy is electric. Skyscrapers stretch toward the heavens, and neon lights dance upon the streets. The vibrant cacophony of urban life is both exhilarating and overwhelming. Amidst the throngs, pockets of solitude emerge—a park's quiet bench or a hidden café—offering respite and reflection within the city's relentless rhythm. It's a place where dreams are pursued, fortunes won and lost, and stories written in the asphalt and steel. The city is an unceasing tide of humanity, each person a character in a sprawling narrative. Amidst the urban tumult, one can find solace in the pockets of stillness and the knowledge that the city is a crucible of aspiration, creativity, and diversity.")
        strings.append("Beneath the ocean's surface lies an enchanting world. Coral reefs teem with life, and the vibrant colors of fish and corals create a mesmerizing spectacle. A delicate balance prevails within this undersea wonderland. As sunlight filters down through the water, it's a poignant reminder of the urgent need to protect our planet's diverse ecosystems. Every creature, from the smallest shrimp to the largest shark, plays a vital role in this intricate dance of life. The coral gardens are delicate and resilient, harboring species yet to be discovered. Preserving the ocean's depths is not just an ecological imperative but an acknowledgment of the profound beauty that thrives beneath the waves.")
        strings.append("Amidst the bustling marketplace, the air is alive with exotic scents. Vendors from distant lands peddle their wares-silk textiles, pungent spices, and intricate jewelry. The aroma is a heady blend of cardamom, cinnamon, and sandalwood. Every step unveils a new sensory adventure, weaving a rich tapestry of fragrances that lingers in the memory. The marketplace is a bustling crossroads of cultures and trade, where spices from the East meet textiles from the West, and where the history of commerce is palpable. These scents and spices transcend geography, invoking the spirit of exploration and exchange that has connected societies for centuries.")
        strings.append("The ancient forest stands as a sentinel of time. Trees with gnarled limbs have borne witness to centuries of life's cycles. Nature's rhythms persist, unfazed by the world's chaos. The forest provides sanctuary, offering solace and renewal to those who venture within its emerald depths. It's a place where ancient wisdom whispers through the leaves, and every step is a communion with the echoes of countless lives. In the heart of the forest, the boundaries between the material and the ethereal blur, allowing the weary soul to find rejuvenation.")
        strings.append("In the library's hushed ambiance, the scent of aged books is comforting. Dusty tomes line the shelves, holding the knowledge and stories of countless generations. The quietude offers respite, a haven for seekers of wisdom to find companionship in the written word. Each book is a gateway to worlds uncharted, a testament to the power of human imagination and the enduring legacy of knowledge. The library is a sanctuary of enlightenment, where the past and the future coexist, and every page turned is a journey through time and space.")
        strings.append("At the mountain's summit, a cool breeze caresses the faces of adventurers who have scaled great heights. The vista unfolds with valleys and peaks stretching to the horizon. It's a testimony to human determination and nature's grandeur, providing a profound sense of accomplishment and connection. The world's vastness stretches to the distant horizons, and at this pinnacle, a sense of boundless possibility and unity with the universe is palpable. The mountain is a testament to the resilience and indomitable spirit of the human quest for exploration and self-discovery.")
        strings.append("In the bustling square, a street musician pours their soul into melodies. Passersby pause, drawn to the artistry that brings beauty to daily life. The impromptu gathering of strangers creates a unique sense of community, as music transcends boundaries and for a brief moment, the world is united by its universal language. The street corner becomes a stage where the shared experience of music transcends the diversity of backgrounds, and the power of artistic expression binds hearts and minds.")
        strings.append("By the tranquil lakeside, the water mirrors the cerulean sky, creating a serene tableau. The gentle lap of waves upon the shore and the distant calls of waterfowl blend into a symphony of solitude. It's a place where introspection blooms, and the mind finds respite in nature's calm embrace. The lake reflects the timeless nature of existence, its surface a mirror to one's thoughts and the eternal serenity of the world.")
        strings.append("As the train speeds along, passengers peer out the windows, observing the ever-changing landscape. Each window frames a distinct narrative of the journey, inviting contemplation about the untold stories that lie beyond the horizon. In the shared experience of travel, fleeting connections are formed, and the world's tapestry is woven together. The train is a vessel of adventure, where the world unfolds in motion, and every mile traversed is a testament to human curiosity and the boundless wonders of the world.")
        strings.append("The art gallery's ambiance is reverent, allowing visitors to immerse themselves in the beauty of the artworks. Paintings adorn the walls, each a masterpiece that conveys the artist's emotions and vision. The gallery provides a space for contemplation, where brushstrokes and colors evoke powerful feelings. As visitors wander through the exhibit, they embark on an emotional journey, connecting with the soul of the artists. Art transcends time and culture, and the gallery is a sanctuary where the human spirit is laid bare through creativity. In a world filled with chaos and noise, the gallery stands as a testament to the enduring power of artistic expression and the profound impact of beauty on the human soul.")
        strings.append("The aroma of freshly baked bread wafts from the local bakery, enveloping the neighborhood in a comforting embrace. The ovens work tirelessly, producing a symphony of crusty loaves and sweet pastries. The bakery is more than a place to satisfy hunger; it's a cornerstone of the community. Locals gather here to share stories and laughter, building connections that transcend the simple act of purchasing bread. With each bite, there's a taste of tradition, family recipes passed down through generations. The bakery is a testament to the enduring love for simple pleasures and the power of food to bring people together.")
        strings.append("The serene garden unfurls in shades of green and blossoms with vibrant colors. Fragrant flowers beckon to bees and butterflies, creating a harmonious dance of life. Amidst the tranquil landscape, there's a sense of timelessness. The garden is a sanctuary of growth and renewal, where nature's wisdom flourishes. It offers a poignant reminder of the beauty that surrounds us and the importance of preserving the delicate balance of the natural world.")
        strings.append("Within the classroom's walls, students embark on a journey of discovery. Books and whiteboards fill the room, and eager minds gather to learn. The atmosphere is charged with curiosity and the promise of knowledge. The classroom is a hallowed space where ideas are born, and the pursuit of wisdom is paramount. It's a place where teachers inspire, and students aspire to new heights. Every desk holds the potential for innovation and progress, and each student is a testament to the power of education to shape the future.")
        strings.append("Beneath the vast starlit sky, the universe unfolds its secrets. The night's canvas is dotted with constellations that have guided explorers for centuries. Each twinkling star is a beacon of hope and wonder, inviting the contemplation of humanity's place in the cosmos. Under the celestial dome, Earth seems small, and the universe boundless. The night sky is a reminder of our connection to the universe, a testament to human curiosity and the never-ending quest to explore the cosmos.")
        strings.append("Amidst the grandeur of the concert hall, music fills the air. The orchestra's harmony and the soloist's skill weave a spellbinding tapestry of sound. The music transcends language, evoking profound emotions in those who listen. Within the concert hall's walls, there's a shared journey of emotions, a connection formed through the collective experience of melody and rhythm. The concert hall is a testament to the power of music to unite hearts and minds and convey the depths of human emotion.")
        strings.append("Alongside the riverbank, the water's current flows steadily. It's a place of contemplation, where the world's reflections shimmer and dance. The gentle murmur of the river soothes the soul, and the rustling of leaves in the breeze creates a tranquil symphony. The riverbank is a sanctuary of serenity, where time slows, and the beauty of nature unfolds. It's a reminder of the cyclical nature of life and the enduring peace found in the embrace of the natural world.")
        strings.append("In the bustling marketplace, the air is a fusion of diverse scents. Street vendors offer spices, textiles, and trinkets. The marketplace is a sensory mosaic where cultures converge, and languages intertwine. The vibrant atmosphere is alive with commerce and conversation. Here, the world's diversity is celebrated, and the exchange of goods mirrors the exchange of stories and experiences. The marketplace is a testament to human ingenuity, resilience, and the enduring spirit of trade and cultural exchange.")
        strings.append("As dawn breaks, the city awakens in a symphony of colors. The skyscrapers reflect the golden light, and the city's pulse quickens. It's a place where dreams are pursued, where the streets are a canvas for human ambition. The city's heartbeat is the rhythm of countless lives, each one a part of the sprawling narrative. In the city's embrace, there's an energy that's electrifying and a sense of endless possibility. The city is a testament to human innovation, creativity, and the ceaseless drive to transform dreams into reality.")
        strings.append("Along the coastal path, waves crash against the rocks, creating a hypnotic melody. The sea stretches to the horizon, and the salty breeze carries the promise of adventure. It's a place where the boundary between land and ocean dissolves, and the mysteries of the deep beckon. The coastal path is a testament to the eternal allure of the sea, a reminder of the boundless wonders that await on the water's edge.")
        strings.append("In the heart of the bustling city, the park serves as an oasis of tranquility. Towering trees offer respite from the concrete jungle, and the chirping of birds creates a soothing symphony. The park is a place of reflection, where visitors find solace in the embrace of nature. It's a refuge from the relentless pace of urban life, a sanctuary for contemplation. The park is a testament to the necessity of green spaces in densely populated areas, providing a haven where people can reconnect with the earth and find serenity amidst the chaos.")
        strings.append("Within the pages of a well-worn book, a world of imagination unfolds. Words transport readers to far-off lands and distant times. The book is a gateway to adventures and emotions, a portal to the realm of dreams. Its power lies in its ability to ignite the imagination and kindle the flames of curiosity. The book is a testament to the enduring magic of storytelling and the written word, offering a timeless escape for those who seek it.")
        strings.append("In the kitchen, the clinking of pots and pans accompanies the aromatic symphony of a home-cooked meal. It's a place where recipes passed down through generations come to life. The kitchen is a hub of creativity and comfort, where food becomes a language of love. It's a testament to the power of nourishment and the bond created through shared meals.")
        strings.append("As the sun sets, the sky transforms into a canvas painted with hues of pink and orange. The horizon stretches infinitely, and the world is bathed in the soft glow of twilight. The sunset is a moment of reflection and wonder, a reminder of the beauty in transitions. It's a testament to the ever-changing nature of life and the ephemeral quality of time.")
        strings.append("Beneath the arching branches of an ancient tree, a sense of timelessness prevails. The tree's roots dig deep into the earth, anchoring it for generations. It's a place of solace and shade, where nature's wisdom is on full display. The ancient tree is a testament to the enduring power of the natural world and the importance of preserving the environment.")
        strings.append("In the hushed confines of the library, shelves upon shelves of books line the walls. Each volume is a portal to knowledge and imagination. The library is a sanctuary of learning and reflection, where the echoes of past scholars resonate. It's a place where history and innovation converge, and the pursuit of wisdom is celebrated. The library is a testament to the preservation of human knowledge and the value of intellectual exploration.")
        strings.append("In the artist's studio, colors dance on the canvas, giving life to vibrant scenes and emotions. The studio is a realm of creativity, where the imagination flows freely. It's a place where artists express their inner worlds and translate them into visual poetry. The artist's studio is a testament to the power of artistic expression and the ability to convey the depths of human experience.")
        strings.append("Beneath the twinkling stars, a campfire crackles, casting flickering shadows on the faces of those gathered around. It's a place where stories come to life, where laughter and camaraderie abound. The campfire is a source of warmth and shared memories, a testament to the timeless joy of storytelling and the bond formed through shared experiences.")
        strings.append("Amidst the rolling hills of a vineyard, grapevines stretch towards the sun, bearing clusters of fruit. It's a place where the art of winemaking unfolds, and the earth's bounty is transformed into a libation. The vineyard is a testament to the harmony of nature and craftsmanship, where tradition and innovation intersect, resulting in a glass of liquid poetry.")
        strings.append("In the heart of the city, the marketplace comes alive with the bustle of shoppers and the shouts of vendors. It's a place where the vibrancy of urban life is on full display, and cultures intertwine. The marketplace is a testament to the diverse tapestry of human existence, where the exchange of goods mirrors the exchange of traditions and stories, and where the world's flavors and scents harmoniously coexist.")
        strings.append("The gentle lapping of waves on the shore creates a calming rhythm by the beach. Seagulls wheel overhead, their calls echoing in the salty breeze. The beach is a place of serenity and wonder, where the vastness of the ocean meets the solidity of the land. It's a realm of natural beauty, where the interplay of elements provides a constant source of inspiration. The beach is a testament to the ever-evolving dance between land and sea, where the ebb and flow of tides remind us of the timeless cycle of life.")
        strings.append("In the realm of mathematics, equations and theorems become the tools for deciphering the universe's mysteries. It's a place of pure logic and abstract thought, where numbers and symbols hold the key to understanding complex phenomena. The world of mathematics is a testament to human intellectual achievement, where the pursuit of knowledge takes on a precise and logical form.")
        strings.append("On the stage, actors and actresses breathe life into the characters they portray. The theater is a world of storytelling and transformation, where the boundaries of reality blur. It's a place where emotions are laid bare, and the human condition is explored. The theater is a testament to the power of performance and the enduring appeal of live storytelling.")
        strings.append("Within the vibrant chaos of a bustling market, vendors call out their wares, and shoppers navigate a labyrinth of stalls. The market is a place of commerce and culture, where the exchange of goods is intertwined with the exchange of traditions. It's a vibrant tapestry of sights, sounds, and scents, a testament to the rich diversity of global markets.")
        strings.append("In the depths of the forest, ancient trees loom overhead, their branches forming a protective canopy. The forest is a realm of wonder and mystique, where the interplay of light and shadow creates an otherworldly ambiance. It's a place where nature's secrets are whispered by rustling leaves. The forest is a testament to the primal beauty of untouched wilderness and the enduring connection between humans and the natural world.")
        strings.append("In the artist's atelier, a canvas takes shape as paintbrushes dance with vivid colors. The atelier is a sanctuary of creative expression, where inspiration flows freely. It's a realm of imagination, where artists breathe life into their visions. The artist's atelier is a testament to the transformative power of art and the endless possibilities it offers.")
        strings.append("In the heart of a vibrant metropolis, skyscrapers stretch towards the heavens, forming a cityscape that never sleeps. The city is a hub of energy and ambition, where cultures and ideas converge. It's a place where innovation and tradition coexist, shaping the future of humanity. The city is a testament to the dynamism of urban life and the human spirit's indomitable drive for progress.")
        strings.append("Deep in the embrace of the mountains, peaks touch the sky, and valleys cradle hidden treasures. The mountains are a realm of grandeur and mystery, where the majesty of nature is on full display. It's a place where the earth's rugged beauty invites exploration and reverence. The mountains are a testament to the resilience and magnificence of the natural world.")
        strings.append("Along the riverbanks, willow trees dip their branches into the water's mirror-like surface. The river is a conduit of life and history, where civilizations have flourished and journeys begun. It's a place where the steady flow of water carries the stories of time. The river is a testament to the fluidity of existence and the enduring legacy of waterways.")
        strings.append("In the serene confines of a garden, blossoms unfurl in vibrant hues and leaves whisper in the breeze. The garden is a haven of beauty and serenity, where the earth's treasures are cultivated. It's a place of respite and contemplation, where nature's harmony invites reflection. The garden is a testament to the art of cultivation and the enchanting balance of flora and fauna.")
        strings.append("The library, a sanctuary of knowledge, is a realm where the wisdom of the ages resides. Rows of books, standing like sentinels, house the collective thoughts of humanity. The library is a place of quiet contemplation, where minds can roam through history, science, and art. It's a haven for those seeking answers, a testament to the enduring quest for understanding.")
        strings.append("In the bustling streets of a foreign city, the vibrant tapestry of cultures comes alive. The city is a melting pot of traditions, a place where languages, customs, and cuisines intermingle. It's a world of constant movement, where the urban rhythm pulses through the veins of its inhabitants. The city is a testament to the richness of diversity and the human capacity for adaptation.")
        strings.append("Beneath the open sky, a vast desert stretches to the horizon, its dunes and sands forming an arid landscape. The desert is a realm of desolation and beauty, where the harshness of nature meets the wonder of the untouched. It's a place where solitude and reflection become companions. The desert is a testament to the earth's extremes and the allure of the barren landscape.")
        strings.append("Deep within the heart of a historical museum, relics from bygone eras whisper of the past. The museum is a repository of time's artifacts, where ancient wonders are preserved. It's a place of reverence for history, where each exhibit reveals a chapter of human civilization. The museum is a testament to the enduring importance of preserving heritage.")
        strings.append("In a thriving workshop, artisans wield their craft with precision and passion. The workshop is a domain of creation and craftsmanship, where raw materials are transformed into exquisite works. It's a place where skill and imagination merge, giving birth to objects of artistry. The workshop is a testament to the indomitable spirit of human creativity.")
        strings.append("Beneath a star-studded sky, the great expanse of the universe unfolds. The night sky is a canvas of wonder, where constellations and galaxies ignite the imagination. It's a realm of cosmic mysteries and infinite possibilities, where humanity's place in the cosmos is pondered. The night sky is a testament to the boundless curiosity of human existence.")
        strings.append("Within the tranquil embrace of a chapel, the hallowed silence offers solace to those who seek it. The chapel is a sanctuary of faith and reflection, where prayers ascend heavenward. It's a place of spiritual communion, where the divine presence is felt. The chapel is a testament to the enduring power of faith and the human need for transcendence.")
        strings.append("Amidst the vibrant colors of an art studio, canvases come to life as brushes and palettes unite. The studio is a realm of artistic expression, where visions take shape. It's a place where emotions are channeled onto the canvas, and stories are told through colors. The studio is a testament to the boundless potential of creative imagination.")
        strings.append("In the verdant embrace of a forest, life teems in all its forms, from towering trees to tiny insects. The forest is a world of interconnected ecosystems, where the delicate balance of nature unfolds. It's a realm of biodiversity and symbiosis, where the circle of life is tangible. The forest is a testament to the intricate web of life on Earth.")
        strings.append("Along the tranquil banks of a river, reflections dance on the water's surface, mirroring the world above. The river is a source of life and tranquility, where the eternal flow of water connects landscapes. It's a place where the rippling currents symbolize the passage of time. The river is a testament to the continuity and cyclical nature of existence.")
        sen = strings[random.randrange(0,49)]
        return sen
    
   
    #word count
def senWordCount(sentence):
        count = 1
        for i in sentence:
            if(i == ' '):
                count+=1
        return count        
    
def getSpaces(sentence): #returns locations of spaces
        spaceloc = []
        count = 0
        for i in sentence:
            if(i == ' '):
                spaceloc.append(count)
            count+=1
        return spaceloc
        
def breakintoWords(sentence): #No longer needed
        words = []
        spaceloc = getSpaces(sentence)
        words.append(sentence[:spaceloc[0]])
        for i in range (1,senWordCount(sentence)-1):
            words.append(sentence[spaceloc[i-1]+1:spaceloc[i]])
        words.append(sentence[spaceloc[len(spaceloc)-1]+1:])
        return words
            

            
    
        

